CREATE TABLE tokens (    
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    member_id INT NOT NULL,    
    token VARCHAR(128) NOT NULL UNIQUE,    
    token_expiry DATETIME NOT NULL,    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME,
    CONSTRAINT FK_members_token FOREIGN KEY (member_id)
    REFERENCES members(id)
)ENGINE=InnoDB; 
