CREATE TABLE tokens (    
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(50) NOT NULL,    
    token_expiry DATETIME NOT NULL,    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME,
    CONSTRAINT FK_users_tokens FOREIGN KEY (user_id)
    REFERENCES users(id)
)ENGINE=InnoDB; 
