CREATE TABLE books (    
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	inventory_number VARCHAR(255),
	cover_img VARCHAR(255),
	author VARCHAR(255),
	call_number_author VARCHAR(255),
	title VARCHAR(255) NOT NULL,
	call_number_title VARCHAR(255),
	publisher VARCHAR(255),
	year INT, 
	city VARCHAR(20),
    price INT,
    quantity INT NOT NULL,
    remain INT NOT NULL,
    total_page INT,
    entry_date DATETIME,
	funding_source VARCHAR(20),
	status ENUM('baik', 'tidak baik'),
    summary TEXT,
    category_id VARCHAR(20),
    CONSTRAINT FK_category FOREIGN KEY(category_id)
    REFERENCES categories(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME
)ENGINE=InnoDB; 
