CREATE TABLE users (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    class VARCHAR(50),
    is_verified BOOL NOT NULL DEFAULT FALSE,
    role_id INT NOT NULL,
	absence_number TINYINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME,
    CONSTRAINT FK_users_roles FOREIGN KEY (role_id)
    REFERENCES roles(id)
)ENGINE=InnoDB;
