CREATE TABLE ratings (    
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    book_id INT NOT NULL,
    member_id INT NOT NULL,
    rating INT,
    CONSTRAINT FK_book FOREIGN KEY (book_id)
    REFERENCES books(id),
    CONSTRAINT FK_member_rating FOREIGN KEY (member_id)
    REFERENCES members(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME
)ENGINE=InnoDB; 


