CREATE TABLE members (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    class VARCHAR(255),
    profile_img VARCHAR(255),
    is_verified BOOL NOT NULL DEFAULT FALSE,
    role_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME,
    CONSTRAINT FK_members_roles FOREIGN KEY (role_id)
    REFERENCES roles(id)
)ENGINE=InnoDB;
